import Link from 'next/link'
import PageHeader from '@/components/ui/page-header'
import Reveal from '@/components/ui/reveal'
import SectionHeading from '@/components/ui/section-heading'
import { Zap, Shield, Leaf, TrendingUp, ArrowRight } from 'lucide-react'
import { images } from '@/lib/images'

const benefits = [
  {
    icon: Leaf,
    title: 'Clean',
    description:
      'Nuclear energy produces zero direct carbon emissions during operation. A single nuclear plant prevents millions of tons of CO₂ annually compared to fossil fuel alternatives.',
  },
  {
    icon: Zap,
    title: 'Reliable',
    description:
      'Nuclear plants operate 24/7 regardless of weather conditions, providing consistent baseload power. Our fleet achieves capacity factors exceeding 90%.',
  },
  {
    icon: Shield,
    title: 'Safe',
    description:
      'Decades of engineering, regulation, and operational discipline have made nuclear one of the safest forms of energy production measured per unit of electricity generated.',
  },
  {
    icon: TrendingUp,
    title: 'Efficient',
    description:
      'A small amount of nuclear fuel produces an enormous amount of energy. One uranium fuel pellet — roughly the size of a fingertip — contains as much energy as one ton of coal.',
  },
]

export default async function NuclearEnergyPage() {
  return (
    <>
      <PageHeader
        eyebrow="Nuclear Energy"
        title="Nuclear Energy"
        description={
          <>
            Nuclear energy is the most energy-dense, reliable, and clean source of baseload power
            available today. It provides approximately 10% of the world&apos;s electricity — and is
            essential to meeting global decarbonization targets.
          </>
        }
        image={images.heroPlant}
      />

      {/* Why Nuclear */}
      <section className="py-24 md:py-32">
        <div className="mx-auto max-w-7xl px-6 lg:px-8">
          <SectionHeading
            title="Why Nuclear Energy"
            subtitle="As the world demands more electricity with fewer emissions, nuclear energy stands apart as the proven, scalable solution."
          />
          <div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
            {benefits.map((b, i) => (
              <Reveal key={b.title} delay={i * 0.08}>
                <div
                  className="h-full rounded-2xl border border-slate-200 bg-white p-8 shadow-sm transition-all hover:shadow-md hover:border-cyan-200"
                >
                  <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-cyan-500/10">
                    <b.icon className="h-6 w-6 text-cyan-500" />
                  </div>
                  <h3 className="mt-5 text-xl font-bold text-navy-900">{b.title}</h3>
                  <p className="mt-3 text-sm text-slate-600 leading-relaxed">{b.description}</p>
                </div>
              </Reveal>
            ))}
          </div>
        </div>
      </section>

      {/* Key Stat */}
      <section className="bg-cyan-500 py-20">
        <div className="mx-auto max-w-7xl px-6 lg:px-8 text-center">
          <Reveal>
            <p className="text-5xl md:text-6xl font-bold text-white tracking-tight">~10%</p>
            <p className="mt-4 text-lg text-cyan-50 max-w-2xl mx-auto">
              of the world&apos;s electricity is generated by nuclear power — more than any single
              renewable source. In over 30 countries, nuclear provides reliable, clean baseload energy
              that complements wind and solar.
            </p>
          </Reveal>
        </div>
      </section>

      {/* Energy Lifecycle */}
      <section className="bg-slate-50 py-24 md:py-32">
        <div className="mx-auto max-w-7xl px-6 lg:px-8">
          <SectionHeading
            title="The Nuclear Energy Lifecycle"
            subtitle="From mining to decommissioning, the nuclear fuel cycle is tightly regulated at every stage."
            centered
          />
          <div className="mt-16 grid gap-4 md:grid-cols-2 lg:grid-cols-5">
            {[
              { step: '1', title: 'Mining & Milling', description: 'Uranium ore is extracted and processed into yellowcake (U₃O₈).' },
              { step: '2', title: 'Enrichment & Fuel Fabrication', description: 'Uranium is enriched and formed into fuel assemblies for reactor use.' },
              { step: '3', title: 'Reactor Operation', description: 'Controlled fission generates heat, producing steam that drives turbines.' },
              { step: '4', title: 'Waste Management', description: 'Spent fuel is cooled, stored, and managed through established protocols.' },
              { step: '5', title: 'Decommissioning', description: 'At end of life, facilities are safely decommissioned and sites restored.' },
            ].map((s, i) => (
              <Reveal key={s.step} delay={i * 0.08}>
                <div className="h-full relative rounded-2xl border border-slate-200 bg-white p-6 text-center shadow-sm">
                  <span className="flex h-10 w-10 mx-auto items-center justify-center rounded-full bg-navy-900 text-sm font-bold text-white">
                    {s.step}
                  </span>
                  <h3 className="mt-4 text-lg font-bold text-navy-900">{s.title}</h3>
                  <p className="mt-2 text-sm text-slate-600 leading-relaxed">{s.description}</p>
                </div>
              </Reveal>
            ))}
          </div>
        </div>
      </section>

      {/* CTAs */}
      <section className="py-24 md:py-32">
        <div className="mx-auto max-w-7xl px-6 lg:px-8">
          <SectionHeading
            title="Learn More"
            subtitle="Explore the technology, safety practices, and innovation driving the future of nuclear energy."
            centered
          />
          <div className="mt-12 grid gap-6 sm:grid-cols-3">
            {[
              { href: '/nuclear-energy/technology', title: 'Reactor Technology', description: 'Explore the reactor types we operate and develop.' },
              { href: '/nuclear-energy/safety', title: 'Nuclear Safety', description: 'Learn about our multi-layered approach to safety.' },
              { href: '/innovation', title: 'Innovation', description: 'See how we are pioneering the next generation of energy.' },
            ].map((c, i) => (
              <Reveal key={c.href} delay={i * 0.08}>
                <Link
                  href={c.href}
                  className="group flex h-full flex-col rounded-2xl border border-slate-200 bg-white p-8 shadow-sm transition-all hover:shadow-md hover:border-cyan-200"
                >
                  <h3 className="text-xl font-bold text-navy-900 group-hover:text-cyan-500 transition-colors">
                    {c.title}
                  </h3>
                  <p className="mt-2 text-sm text-slate-600">{c.description}</p>
                  <span className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-cyan-500">
                    Learn More <ArrowRight className="h-4 w-4" />
                  </span>
                </Link>
              </Reveal>
            ))}
          </div>
        </div>
      </section>
    </>
  )
}
